trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build code'

- script: dotnet test --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'Run tests'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish integration tests coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'test/Usemam.IdentityServer4.KeyRack.IntegrationTests/coverage.cobertura.xml'
