trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build code'
- task: VSTest@2
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: test/**/*Tests.dll
    codeCoverageEnabled: True
  displayName: 'Run tests'
